### ISSUE TITLE
Prowlarr is only downloaden first episode of season 

### ISSUE THREAD

**Issue by arjanterheegde** [dreulavelle/Prowlarr-Indexers#10]
Hi,

Sonarr is only downloading the first episode of the season. I’ve already updated my torrentio file (with the update from yesterday) and restarted Prowlarr. 

For example the serie “ The Lord of the Rings: The Rings of Power”

what could be wrong?

Kind regards,

Arjan

**Comment by arjanterheegde** [comment]
When i'm using 1337x as indexer everything works fine so it looks like it has something to do with Torrentio.yml?

**Comment by chrisngobanh** [comment]
This is related to #12. As a workaround, you need to drop the file size of your quality profile so that it meets the threshold to pick up a season pack instead of a single episode.

**Comment by dreulavelle** [comment]
This should be fixed in latest versions.. I never had this issue though.
