### ISSUE TITLE
Prowlarr is reporting the size of the first file on Season packs

### ISSUE THREAD

**Issue by nacho-herrera** [dreulavelle/Prowlarr-Indexers#12]
Hi, I saw that many series get not grabbed by Sonarr because the file size for a season pack is informed wrong and thus is filtered out by the media quality settings.

For example:
![image](https://github.com/dreulavelle/Prowlarr-Indexers/assets/65458529/58ee65ff-4dbf-4613-9f07-df05711bd514)
Season 11 shows 3.3 GB but when added to Rdtclient, the size is 35.77 GB
![image](https://github.com/dreulavelle/Prowlarr-Indexers/assets/65458529/31485205-86f5-41ca-a815-f746ed80899d)
Each file is about 3356 MB so I think that the indexer is returning the size of a file instead of the complete torrent.
![image](https://github.com/dreulavelle/Prowlarr-Indexers/assets/65458529/c56e1843-3d54-42ba-a3c3-1bdaeda1f092)

**Comment by jrobinfo** [comment]
I have the same issue also

**Comment by tjukkie** [comment]
Same.

**Comment by chrisngobanh** [comment]
Does anyone have a good fix for this besides just reducing the file size threshold?

**Comment by nacho-herrera** [comment]
In my research i found out that the issue is from Torrentio and how them returns the information. 
For example following with my previous example:
query URL:  https://torrentio.strem.fun/providers=yts,eztv,rarbg,1337x,thepiratebay,kickasstorrents,torrentgalaxy,magnetdl,horriblesubs,%7Csort=size%7CClimit=1%7Crealdebrid=[REDACTED]%7Cdebridoptions=nodownloadlinks/stream/series/tt0106179:11:1.json

```
{
    "streams": [
          {...}, 
          {
               "name": "[RD+] Torrentio\n1080p",
               "title": "The.X-Files.S11.1080p.BluRay.x264-SHORTBREHD[rartv]\nThe.X-Files.S11E01.1080p.BluRay.x264-SHORTBREHD.mkv\n👤 2 💾 3.28 GB ⚙️ RARBG",
               "url": "https://torrentio.strem.fun/realdebrid/[REDACTED]/644993cd60a27f78d1b31cc855e0af2ca3737b5c/null/21/The.X-Files.S11E01.1080p.BluRay.x264-SHORTBREHD.mkv",
               "behaviorHints": {
                    "bingeGroup": "torrentio|644993cd60a27f78d1b31cc855e0af2ca3737b5c"
               }
          },
          {...}
     ],
    "cacheMaxAge": 3600,
    "staleRevalidate": 14400,
    "staleError": 604800
}
```

I think there is no possible solution, at least from this library as the source returns the information this way.

**Comment by dreulavelle** [comment]
This is a Torrentio issue guys.. has nothing to do with this indexer unfortunately..
