### ISSUE TITLE
Just installed and tried a search within prowalarr

### ISSUE THREAD

**Issue by Q-efx** [dreulavelle/Prowlarr-Indexers#13]
I always get the same two files back?

![image](https://github.com/dreulavelle/Prowlarr-Indexers/assets/42732/463d03de-4269-47bc-8dee-ec63be1645eb)

**Comment by tjukkie** [comment]
Same result here...

**Comment by tjukkie** [comment]
> I always get the same two files back?
> 
> ![image](https://private-user-images.githubusercontent.com/42732/298846753-463d03de-4269-47bc-8dee-ec63be1645eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwOTE5MTIsIm5iZiI6MTcwNjA5MTYxMiwicGF0aCI6Ii80MjczMi8yOTg4NDY3NTMtNDYzZDAzZGUtNDI2OS00N2JjLThkZWUtZWM2M2JlMTY0NWViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDEwMjAxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmZWY2NDZhMmJiOTU5NDZkNTY4Njc3MWNhYzZjYjdjOTMyNWFmY2ZhNGEyM2UyNThiYjM4N2I1YTgwNDJiMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w2oPoRzMC7Pj5scCdZbQoGVwOXxomBekGzx6ql_aFbM)

Just don't search from prowlarr itself. Use the *arrs to do the searching and it works.

**Comment by minhiscus** [comment]
getting the same interactive search results.

**Comment by MrMookdog** [comment]
Yeah I am having the same issue only shows 2 links for old shows

**Comment by dreulavelle** [comment]
You guys are searching wrong.. have to search by changing the search type to movie or show.. then use the specific syntax to do manual searches.

![image](https://github.com/dreulavelle/Prowlarr-Indexers/assets/5782630/ab974cd7-14ca-425c-b19c-2c358369dcb6)
