### ISSUE TITLE
Making torrention be mote rssish

### ISSUE THREAD

**Issue by fborch** [dreulavelle/Prowlarr-Indexers#17]
This setup works very well for me, and whenever I add a new movie or series in sonarr it works pretty well. However, seeing as torrention through prowlarr doesnt work as RSS, the arrs are having trouble finding any new content. Especially with ongoing shows in sonarr, this is a problem? Is there any way to make this behave more like stock indexers in prowlarr, or another way to schedule searches in the Arrs?

**Comment by dreulavelle** [comment]
Torrentio doesnt support RSS, so the torrentio indexer wont either.
