### ISSUE TITLE
possible to only return [RD+] results and filter out [RD download] results? Or prioritize RD+?

### ISSUE THREAD

**Issue by djsecrist** [dreulavelle/Prowlarr-Indexers#18]
This is mostly working very well for me using the Torrentio custom indexer.  However, sometimes *arr ends up adding some non-cached files ([RD download]) to the rdtclient download queue when there are already cached files ([RD+]) available on RD.  Is this something that can be changed in my settings in either Prowlarr or Radarr?  Do I need to customize the Radarr profiles to downgrade the [RD download] results?  How would I do that?  I tried setting a Custom Format with a Preferred Word regex to match [RD download] and then set the Profile to reduce the score with a match, but that didn't seem to work.  Also, how would I get this to work using the Knightcrawler custom indexer, too?

See example below from the Torrentio query result in Prowlarr:

Snipped from the Prowlarr history...  Radarr selected this non-cached file because REMUX is my desired quality:
```
    {
      "name": "[RD download] Torrentio\n1080p",
      "title": "Movie.43.2013.1080p.BluRay.Remux.AVC.DTS-HD.MA.5.1-HDRemuXHD\n👤 1 💾 18.05 GB ⚙️ ThePirateBay",
      "url": "https://torrentio.strem.fun/realdebrid/***redacted***/Movie.43.2013.1080p.BluRay.Remux.AVC.DTS-HD.MA.5.1-HDRemuXHD",
      "behaviorHints": { "bingeGroup": "torrentio|1080p|BluRay REMUX|avc" }
    },
```

When this file (or many others) would be more desired since it's already cached:
```
    {
      "name": "[RD+] Torrentio\n1080p",
      "title": "Movie.43.2013.1080p.BluRay.x265-RARBG\n👤 10 💾 1.53 GB ⚙️ RARBG",
      "url": "https://torrentio.strem.fun/realdebrid/***redacted***/Movie.43.2013.1080p.BluRay.x265-RARBG",
      "behaviorHints": { "bingeGroup": "torrentio|1080p|BluRay|x265" }
    },
```

**Comment by dreulavelle** [comment]
We already return cached results if you put your rd key in when you add the indexer
