### ISSUE TITLE
self-hosted Knightcrawler not returning results

### ISSUE THREAD

**Issue by djsecrist** [dreulavelle/Prowlarr-Indexers#19]
I'm trying to get the self-hosted Knightcrawler custom indexer to work with Prowlarr. Knightcrawler has been working for days and my postgres database looks to be full of goodness.  However, the only search results that ever come back are for the test movie and show that I put in the prowlarr custom config yaml file.  I can see a movie being processed by the consumer, search for it in Prowlarr using the IMDB id, and get nothing.  If I search by name I always get my test movie returned and nothing else.  It seems like Knightcrawler is working as expected, but either the Prowlarr custom indexer isn't right or the Knightcrawler Addon doesn't work the way I think it should in this case...  I would love any help or tips on what I might be doing wrong.  The only change I made to the YAML file was to change the URL to my self-hosted Knightcrawler docker container, and I know that the communication between the containers is working properly.  Thanks!

**Comment by djsecrist** [comment]
It was pointed out to me on the Knightcrawler Discord chat that searches from within Prowlarr never seem to return results for some reason.  However, performing the searches (either automated or interactive) from Sonarr or Radarr does return results.  So, I think this can be closed.  It would be good to include this in the documentation as an FYI for others that may be thinking the same thing as I was...

**Comment by skearney414** [comment]
How did you get around adding this to the arrs? :)

**Comment by djsecrist** [comment]
I used the yaml files from this repo, put them in the custom definitions folder, edited for my hostnames (easiest way is to ensure that your prowlarr and knightcrawler are on the same network), rebooted prowlarr, and then added the new indexer.  As said above, the searches directly in prowlarr never return the correct results but they do when called from Sonarr and Radarr.
