### ISSUE TITLE
Unable to access torrentio.strem.fun, blocked by CloudFlare Protection.

### ISSUE THREAD

**Issue by AdamGoodApp** [dreulavelle/Prowlarr-Indexers#28]
Trying to add Torrentio to Prowlar but get the error . Running on a Oracle Cloud VM.

`Unable to access torrentio.strem.fun, blocked by CloudFlare Protection.`

<img width="695" alt="Screenshot 2024-04-25 at 20 18 54" src="https://github.com/dreulavelle/Prowlarr-Indexers/assets/4471245/bb7376f0-4159-4b18-957f-c77ee0c97485">

**Comment by ruizlenato** [comment]
Same here

**Comment by pablobaro** [comment]
Did you find a solution to it? Thanks

**Comment by AdamGoodApp** [comment]
@pablobaro I contacted Elf team on Discord and they changed some Kubernetes config for me to solve it.

**Comment by pablobaro** [comment]
@AdamGoodApp you have the URL?

**Comment by sire6** [comment]
Yes please do you have the URL?

**Comment by AdamGoodApp** [comment]
@pablobaro @sire6 Contact them here https://docs.elfhosted.com/get-help/

**Comment by hashhopper-hub** [comment]
This issue has come back and that discord seems to be non-existent now. Any one else resolve this issue on their own? If so how?

**Comment by hashhopper-hub** [comment]
Yeah PIA seems to be blocked now as well. Trying to think of a creative way to protect the traffic using non-debrid downloads but leave VPN off for the debrid ones.
