### ISSUE TITLE
elfhosted-public: ValidationFailure: Error while parsing field=infohash, selector=url, value=<null>: Selector "" didn't match

### ISSUE THREAD

**Issue by soredake** [dreulavelle/Prowlarr-Indexers#29]
![image](https://github.com/dreulavelle/Prowlarr-Indexers/assets/5204968/1a423974-4d6a-4b93-a5c1-776927c1f15b)

```

Unable to connect to indexer, check the log above the ValidationFailure for more details. Error while parsing field=infohash, selector=url, value=<null>: Selector "" didn't match { "name": "knightcrawler\n1080p", "title": "Fight Club\nFight Club 1999 BluRay 1080p DTS-HD MA 5 1 AVC REMUX-FraMeSToR.mkv\n💾 29.25 GB", "infoHash": "6686ce8f446670739a421c836651c8d412779e29", "fileIdx": 0, "behaviorHints": { "bingeGroup": "knightcrawler|1080p|FraMeSToR" } }

```

**Comment by uniextra** [comment]
Same problem here. 
Tested with torrentio.yml and elfhosted-public.yml with the same result 
Prowlarr version 1.17.2.4511

**Comment by dprieto24** [comment]
Has this problem been solved? Got the same issue
![Captura de pantalla 2024-11-22 182728](https://github.com/user-attachments/assets/917178c3-0517-49d6-9410-0da190cbf7d1)

**Comment by koenigelias-prog** [comment]
same problem here:
Unable to connect to indexer, check the log above the ValidationFailure for more details. Error while parsing field=infohash, selector=infoHash, value=<null>: Selector "infoHash" didn't match JSON content

**Comment by 9acca9** [comment]
and me too.
Solutions?
thanks
