### ISSUE TITLE
File size for season packs reported incorrectly

### ISSUE THREAD

**Issue by nrlcode** [dreulavelle/Prowlarr-Indexers#3]
When searching for season packs for TV Shows, the file size is reported incorrectly. It appears to just be grabbing one of the files and not the size of the entire season pack.

**Comment by dreulavelle** [comment]
I realized this one too actually while comparing what Sonarr saw vs what Rdt saw it as. Unfortunately this prowlarr indexer can only scrape the page from Torrentio. So this can't be fixed from the Prowlarr Indexer, but instead has to be fixed on Torrentio.
