### ISSUE TITLE
Zilean: unable to parse

### ISSUE THREAD

**Issue by fborch** [dreulavelle/Prowlarr-Indexers#42]
Unable to connect to indexer, check the log above the ValidationFailure for more details. Error while parsing field=title, selector=rawTitle, value=<null>: Selector "" didn't match { "info_hash": "3f45ee345c966c6b23c866374f45480475899f51", "resolution": [ "1080p" ], "year": 1999, "remastered": true, "codec": [ "H.264" ], "audio": [], "quality": [], "episode": [], "season": [], "language": [], "parsed_title": "Fight Club", "raw_title": "Fight Club 1999 REMASTERED 1080p BluRay REMUX AVC DTS-HD MA 5 1-FGT mkv", "size": 31138330573, "category": "movie", "imdb_id": "tt0137523", "imdb": { "imdbId": "tt0137523", "category": "movie", "title": "Fight Club", "adult": false, "year": 1999 } }

**Comment by fborch** [comment]
Using ipromknight/zilean:latest and lscr.io/linuxserver/prowlarr:latest

**Comment by Pukabyte** [comment]
Updated to support latest update of Zilean that changed the output of a request.

Please try it and report if it works for you

**Comment by fborch** [comment]
I'm able to add it fine to Prowlarr again, but it seems like it is only searching for the examples from the config (House of the dragon in this case:

![bilde](https://github.com/user-attachments/assets/8d25bba1-9356-4b3b-a777-5a0b7f9748c9)

**Comment by Pukabyte** [comment]
[](https://github.com/dreulavelle/Prowlarr-Indexers/pull/44)
I have  updated it with this PR, please check it out and let me know how you get on

**Comment by fborch** [comment]
Fixed
