### ISSUE TITLE
Suggestion: Add Zilean ElfHosted option.

### ISSUE THREAD

**Issue by ICE0124** [dreulavelle/Prowlarr-Indexers#53]
https://zilean.elfhosted.com
Add as a base Url and now you can use Elfhosted's Zilean instance.
Could you add this to the Zilean indexer?

**Comment by maindust** [comment]
I saw the adding the url to the existing yaml, I prefer to have a different custom indexer all together and have PR’d here. https://github.com/dreulavelle/Prowlarr-Indexers/pull/59
